export const TOOLBAR_HEIGHT = 38
export const TAB_STRIP_HEIGHT = 30
export const NAV_BAR_HEIGHT = 32
export const BROWSER_CHROME_HEIGHT = TAB_STRIP_HEIGHT + NAV_BAR_HEIGHT
export const BROWSER_TOP = TOOLBAR_HEIGHT + BROWSER_CHROME_HEIGHT
export const DEFAULT_PANE_FRACTION = 2 / 3
